[package]
name = "rtcon"
version = "0.1.0"
authors = ["Mark Zuber <mark@zube.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
